import { ReglaSeed } from './index';

/**
 * 10 reglas Cucurbitáceas (Patilla, Ahuyama, Melón) - Sprint 4 AgroField
 * Fuentes: AGROSAVIA, Bayer Vegetables, Portal Frutícola, Wikifarmer
 */
export const reglasCucurbitaceas: ReglaSeed[] = [
  {
    codigo: 'R-CUC-001',
    nombre: 'Mosca blanca cucurbitáceas (vector virus)',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Patilla',
    plagaNombre: 'Mosca blanca',
    severidadMinima: 'media',
    accionSugerida:
      'Plaga más problemática. Vector de virus mosaico. Acción urgente para prevenir epidemia viral.',
    productoSugerido: 'Imidacloprid o Pyriproxyfen',
    dosisRecomendada: 250,
    unidadRecomendada: 'cc/ha',
    metodoAplicacion: 'aspersion_foliar_enves',
    frecuenciaDias: 10,
    prioridad: 5,
    fuenteCientifica: 'Portal Frutícola 2026 - Plagas sandía y melón. Bayer Vegetables.',
  },
  {
    codigo: 'R-CUC-002',
    nombre: 'Minador de hoja cucurbitáceas (Liriomyza)',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Patilla',
    severidadMinima: 'media',
    accionSugerida:
      'Promover parasitoides naturales (Diglyphus). Solo químico si severidad supera 30% follaje afectado.',
    productoSugerido: 'Abamectina o Ciromazina',
    dosisRecomendada: 0.4,
    unidadRecomendada: 'L/ha',
    metodoAplicacion: 'biologico_+_selectivo',
    prioridad: 3,
    fuenteCientifica: 'Hortalizas - Minador hoja cucurbitáceas.',
  },
  {
    codigo: 'R-CUC-003',
    nombre: 'Pulgón Aphis gossypii cucurbitáceas',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Patilla',
    plagaNombre: 'Pulgones',
    severidadMinima: 'media',
    accionSugerida: 'Insecticida sistémico. Vector de virus.',
    productoSugerido: 'Pirimicarb o Imidacloprid',
    dosisRecomendada: 0.5,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_foliar',
    prioridad: 3,
    fuenteCientifica: 'Certis Belchim - Control melón y sandía.',
  },
  {
    codigo: 'R-CUC-004',
    nombre: 'Spodoptera exigua sandía',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Patilla',
    plagaNombre: 'Gusano cogollero',
    severidadMinima: 'media',
    accionSugerida:
      'Monitoreo con feromonas. Aplicar Bacillus thuringiensis o Spinosad para larvas pequeñas.',
    productoSugerido: 'Bacillus thuringiensis',
    dosisRecomendada: 1,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_foliar_dirigida',
    prioridad: 4,
    fuenteCientifica: 'Phytoma - Lepidópteros sandía.',
  },
  {
    codigo: 'R-CUC-005',
    nombre: 'Mildiú polvoriento ahuyama',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Ahuyama',
    severidadMinima: 'media',
    accionSugerida:
      'Fungicida específico. Mejorar circulación de aire. Variedades tolerantes preferibles.',
    productoSugerido: 'Azufre micronizado o Miclobutanil',
    dosisRecomendada: 3,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_foliar',
    frecuenciaDias: 10,
    prioridad: 3,
    fuenteCientifica: 'AGROSAVIA - Cultivo zapallo Cucurbita.',
  },
  {
    codigo: 'R-CUC-006',
    nombre: 'Mildiú velloso cucurbitáceas (Pseudoperonospora)',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Patilla',
    severidadMinima: 'media',
    estacion: 'lluviosa',
    accionSugerida: 'Fungicida cúprico o Metalaxil + Mancozeb. Activo en condiciones húmedas.',
    productoSugerido: 'Metalaxil + Mancozeb',
    dosisRecomendada: 2.5,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_foliar',
    frecuenciaDias: 7,
    prioridad: 4,
    fuenteCientifica: 'Wikifarmer - Enfermedades calabaza.',
  },
  {
    codigo: 'R-CUC-007',
    nombre: 'Virus mosaico cucurbitáceas (CMV, WMV)',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Patilla',
    severidadMinima: 'baja',
    accionSugerida:
      'NO hay tratamiento curativo. Controlar vectores (mosca blanca, pulgones). Eliminar plantas enfermas. Variedades resistentes.',
    metodoAplicacion: 'erradicacion_+_control_vector',
    prioridad: 5,
    fuenteCientifica: 'Bayer Vegetables - Virus mosaico cucurbitáceas.',
  },
  {
    codigo: 'R-CUC-008',
    nombre: 'Antracnosis cucurbitáceas (Colletotrichum)',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Patilla',
    plagaNombre: 'Antracnosis',
    severidadMinima: 'media',
    estacion: 'lluviosa',
    accionSugerida: 'Fungicida preventivo. Eliminar restos vegetales. Rotación.',
    productoSugerido: 'Clorotalonil',
    dosisRecomendada: 2,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_foliar',
    frecuenciaDias: 14,
    prioridad: 3,
    fuenteCientifica: 'UMN Extension - Enfermedades cucurbitáceas.',
  },
  {
    codigo: 'R-CUC-009',
    nombre: 'Rotación cucurbitáceas (no consecutiva 2-3 años)',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Patilla',
    faseAgronomica: 'preparacion',
    accionSugerida:
      'No sembrar cucurbitáceas consecutivamente. Rotar 2-3 años con cereales u hortalizas de otras familias. Reduce Fusarium, antracnosis, virus.',
    prioridad: 4,
    fuenteCientifica: 'Portal Frutícola - Buenas prácticas cucurbitáceas.',
  },
  {
    codigo: 'R-CUC-010',
    nombre: 'Riego ahuyama (Cucurbita moschata)',
    tipoRecomendacion: 'riego',
    cultivoNombre: 'Ahuyama',
    estacion: 'seca',
    diasSinRiegoMinimo: 5,
    accionSugerida:
      'Riego por surcos. Evitar mojar follaje (favorece mildiú). Suelo bien drenado fundamental.',
    dosisRecomendada: 30,
    unidadRecomendada: 'mm/aplicacion',
    metodoAplicacion: 'gravedad',
    frecuenciaDias: 5,
    prioridad: 3,
    fuenteCientifica: 'AGROSAVIA - Cultivo zapallo Cucurbita.',
  },
];
