import { ReglaSeed } from './index';

/**
 * 12 reglas Cacao (Theobroma cacao) - Sprint 4 AgroField
 * Fuentes: Fedecacao, AGROSAVIA, ICA Tulenapa
 */
export const reglasCacao: ReglaSeed[] = [
  {
    codigo: 'R-CACAO-001',
    nombre: 'Moniliasis cacao - control semanal',
    descripcion: 'La moniliasis impacta 40% de la producción anual de cacao en Colombia.',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Cacao',
    plagaNombre: 'Monilia',
    severidadMinima: 'media',
    accionSugerida:
      'Remoción semanal de frutos enfermos. Poda fitosanitaria. Aplicación de fungicidas sistémicos en segundo semestre coincidiendo con lluvias.',
    metodoAplicacion: 'poda_+_remocion_+_cultural',
    frecuenciaDias: 7,
    prioridad: 5,
    fuenteCientifica:
      'Fedecacao - Manejo enfermedades cacao. AGROSAVIA 2016 estrategias Moniliophthora.',
  },
  {
    codigo: 'R-CACAO-002',
    nombre: 'Moniliasis severidad alta - fungicidas sistémicos',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Cacao',
    plagaNombre: 'Monilia',
    severidadMinima: 'alta',
    accionSugerida:
      'Combinar poda fitosanitaria + fungicidas. Triadimefon 1.5 L/ha o Pyracarbolid 2.5 L/ha. Aplicar en segundo semestre.',
    productoSugerido: 'Triadimefon o Pyracarbolid',
    dosisRecomendada: 1.5,
    unidadRecomendada: 'L/ha',
    metodoAplicacion: 'aspersion_+_poda',
    frecuenciaDias: 30,
    prioridad: 5,
    fuenteCientifica: 'ICA Tulenapa Urabá - Control integrado escoba de bruja y moniliasis.',
  },
  {
    codigo: 'R-CACAO-003',
    nombre: 'Escoba de bruja del cacao',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Cacao',
    plagaNombre: 'Escoba de bruja',
    severidadMinima: 'media',
    accionSugerida:
      'Podar y quemar todas las escobas (brotes anormales). Poda fitosanitaria es la principal medida. Sin manejo puede destruir 100% de plantación.',
    metodoAplicacion: 'poda_fitosanitaria_+_quemado',
    frecuenciaDias: 30,
    prioridad: 5,
    fuenteCientifica: 'AGROSAVIA - Ficha técnica Moniliophthora perniciosa. Cadena Cacao CA.',
  },
  {
    codigo: 'R-CACAO-004',
    nombre: 'Mazorca negra cacao (Phytophthora palmivora)',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Cacao',
    plagaNombre: 'Mazorca negra',
    severidadMinima: 'media',
    estacion: 'lluviosa',
    accionSugerida: 'Remoción semanal de mazorcas afectadas. Fungicida cúprico preventivo.',
    productoSugerido: 'Oxicloruro de cobre',
    dosisRecomendada: 3,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_+_remocion',
    frecuenciaDias: 21,
    prioridad: 4,
    fuenteCientifica: 'AGROSAVIA - Control mazorca negra Phytophthora cacao.',
  },
  {
    codigo: 'R-CACAO-005',
    nombre: 'Densidad de siembra cacao',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Cacao',
    faseAgronomica: 'preparacion',
    accionSugerida:
      'Densidad 1100 plantas/ha (distancia 3x3 m). Asociar con sombrío permanente (Cordia, Erythrina, Inga) y temporal (plátano).',
    dosisRecomendada: 1100,
    unidadRecomendada: 'plantas/ha',
    prioridad: 3,
    fuenteCientifica: 'Fedecacao - Manual técnico siembra cacao Colombia.',
  },
  {
    codigo: 'R-CACAO-006',
    nombre: 'Sombrío 40-60% cacao',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Cacao',
    faseAgronomica: 'crecimiento_vegetativo',
    accionSugerida:
      'Mantener sombrío del 40-60%. Sombrío excesivo (>70%) favorece moniliasis. Sombrío escaso (<30%) causa estrés térmico.',
    prioridad: 4,
    fuenteCientifica: 'Fedecacao - Sistemas agroforestales cacao.',
  },
  {
    codigo: 'R-CACAO-007',
    nombre: 'Poda de formación primer año',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Cacao',
    faseAgronomica: 'crecimiento_vegetativo',
    diasDesdeSiembraMinimo: 180,
    diasDesdeSiembraMaximo: 365,
    accionSugerida:
      'Formar 3-5 ramas principales. Eliminar chupones basales. Define arquitectura de la planta para los próximos 30 años.',
    prioridad: 4,
    fuenteCientifica: 'Fedecacao - Cartilla poda cacao.',
  },
  {
    codigo: 'R-CACAO-008',
    nombre: 'Fertilización balanceada cacao',
    tipoRecomendacion: 'fertilizacion',
    cultivoNombre: 'Cacao',
    accionSugerida:
      'NPK balanceado con énfasis en potasio para llenado de mazorca. Análisis de suelo previo.',
    productoSugerido: 'NPK 15-15-15-3MgO o 20-7-19',
    dosisRecomendada: 250,
    unidadRecomendada: 'g/planta',
    metodoAplicacion: 'edafica_corona',
    frecuenciaDias: 90,
    prioridad: 3,
    fuenteCientifica: 'Fedecacao - Manual fertilización cacao Colombia.',
  },
  {
    codigo: 'R-CACAO-009',
    nombre: 'Riego cacao sequía prolongada',
    tipoRecomendacion: 'riego',
    cultivoNombre: 'Cacao',
    estacion: 'seca',
    diasSinRiegoMinimo: 15,
    accionSugerida: 'Riego complementario. Cacao requiere 1500-2500 mm/año bien distribuidos.',
    dosisRecomendada: 125,
    unidadRecomendada: 'L/árbol/semana',
    metodoAplicacion: 'goteo',
    frecuenciaDias: 7,
    prioridad: 3,
    fuenteCientifica: 'Fedecacao - Requerimientos hídricos cacao.',
  },
  {
    codigo: 'R-CACAO-010',
    nombre: 'Cosecha cacao por color',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Cacao',
    faseAgronomica: 'cosecha',
    accionSugerida:
      'Cosechar solo mazorcas maduras (color amarillo/rojo según variedad). Cortar con tijera, NO arrancar. Frecuencia quincenal.',
    frecuenciaDias: 14,
    prioridad: 4,
    fuenteCientifica: 'Fedecacao - Manual cosecha cacao.',
  },
  {
    codigo: 'R-CACAO-011',
    nombre: 'Fermentación cacao post-cosecha',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Cacao',
    faseAgronomica: 'post_cosecha',
    accionSugerida:
      'Fermentar granos 5-6 días en cajón de madera con remoción cada 48h. Es crítico para desarrollar sabor y aroma de chocolate.',
    frecuenciaDias: 2,
    prioridad: 5,
    fuenteCientifica: 'Fedecacao - Beneficio postcosecha cacao.',
  },
  {
    codigo: 'R-CACAO-012',
    nombre: 'Secado cacao a humedad 7-8%',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Cacao',
    faseAgronomica: 'post_cosecha',
    accionSugerida:
      'Secar granos al sol sobre tarima a 7-8% humedad final. Almacenamiento prolongado requiere <7%. Evitar contacto con suelo.',
    prioridad: 5,
    fuenteCientifica: 'Fedecacao - Secado cacao Colombia.',
  },
];
