import { ReglaSeed } from './index';

/**
 * 9 reglas Arroz adicional - Sprint 4 AgroField
 * Fuentes: FEDEARROZ, AgriFarm Colombia, RedAgrícola
 */
export const reglasArrozAdicional: ReglaSeed[] = [
  {
    codigo: 'R-ARRZ-001',
    nombre: 'Pyricularia oryzae arroz (añublo/quemazón)',
    descripcion: 'Enfermedad más limitante del cultivo en el mundo.',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Arroz',
    plagaNombre: 'Pyricularia',
    severidadMinima: 'media',
    accionSugerida:
      'Condiciones favorables: 25-28°C, HR>80%, >12h rocío. Fungicida sistémico preventivo en macollamiento y emergencia panícula.',
    productoSugerido: 'Tricyclazole o Azoxistrobina',
    dosisRecomendada: 0.4,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_foliar',
    frecuenciaDias: 21,
    prioridad: 5,
    fuenteCientifica: 'FEDEARROZ - Manejo integrado Pyricularia oryzae. AgriFarm Colombia.',
  },
  {
    codigo: 'R-ARRZ-002',
    nombre: 'Virus hoja blanca arroz (VHBA)',
    descripcion: 'Cada punto de incidencia reduce rendimiento 266 kg/ha.',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Arroz',
    severidadMinima: 'baja',
    accionSugerida:
      'Variedades resistentes (Fedearroz 50, 67). Control vector Tagosodes orizicolus (Sogata). Tratamiento de semilla con insecticidas.',
    metodoAplicacion: 'prevencion_+_control_vector',
    prioridad: 5,
    fuenteCientifica: 'FEDEARROZ - Virus hoja blanca. RedAgrícola 2023.',
  },
  {
    codigo: 'R-ARRZ-003',
    nombre: 'Sogata arroz (Tagosodes orizicolus)',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Arroz',
    plagaNombre: 'Sogata',
    severidadMinima: 'media',
    accionSugerida: 'Monitoreo desde plántula. Insecticida si supera 5 adultos/golpe de red.',
    productoSugerido: 'Imidacloprid o Thiamethoxam',
    dosisRecomendada: 250,
    unidadRecomendada: 'cc/ha',
    metodoAplicacion: 'aspersion_foliar',
    prioridad: 4,
    fuenteCientifica: 'FEDEARROZ - Manejo Sogata vector VHBA.',
  },
  {
    codigo: 'R-ARRZ-004',
    nombre: 'Mal del pie arroz',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Arroz',
    severidadMinima: 'media',
    accionSugerida:
      'Mejorar drenaje. Aplicar materia orgánica. Rotación con cultivos no gramíneas. No hay fungicida curativo.',
    metodoAplicacion: 'cultural_+_drenaje',
    prioridad: 3,
    fuenteCientifica: 'FEDEARROZ - Cartilla variedades 2024.',
  },
  {
    codigo: 'R-ARRZ-005',
    nombre: 'Arroz: ajustar N-K según T nocturna',
    tipoRecomendacion: 'fertilizacion',
    cultivoNombre: 'Arroz',
    estacion: 'seca',
    accionSugerida:
      'En zonas altas T nocturnas (Caribe), reducir N e incrementar K. Bajo luminosidad alta, mayor respuesta a N. Bajo nubosidad alta, fraccionar N.',
    productoSugerido: 'KCl + Urea',
    dosisRecomendada: 22,
    unidadRecomendada: 'kg K/ton',
    metodoAplicacion: 'edafica',
    prioridad: 3,
    fuenteCientifica: 'FEDEARROZ - Cartilla variedades 2024 (Caribe).',
  },
  {
    codigo: 'R-ARRZ-006',
    nombre: 'Manchado de grano arroz',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Arroz',
    faseAgronomica: 'fructificacion',
    severidadMinima: 'media',
    accionSugerida: 'Fungicida sistémico en floración. Eliminar malezas hospederas. Rotación.',
    productoSugerido: 'Tebuconazol + Trifloxistrobina',
    dosisRecomendada: 0.6,
    unidadRecomendada: 'L/ha',
    metodoAplicacion: 'aspersion_foliar',
    prioridad: 3,
    fuenteCientifica: 'FEDEARROZ - Manchado de grano.',
  },
  {
    codigo: 'R-ARRZ-007',
    nombre: 'Añublo bacterial vaina arroz',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Arroz',
    severidadMinima: 'baja',
    accionSugerida:
      'Variedades resistentes preferibles. Bactericida cúprico si necesario. Rotación.',
    productoSugerido: 'Hidróxido de cobre',
    dosisRecomendada: 2,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_foliar',
    prioridad: 3,
    fuenteCientifica: 'FEDEARROZ - Variedades tolerantes.',
  },
  {
    codigo: 'R-ARRZ-008',
    nombre: 'Densidad siembra arroz secano',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Arroz',
    faseAgronomica: 'siembra',
    accionSugerida:
      'Densidad 80-100 kg semilla/ha en siembra al voleo. 60-80 kg/ha en siembra mecanizada en líneas.',
    dosisRecomendada: 90,
    unidadRecomendada: 'kg semilla/ha',
    prioridad: 3,
    fuenteCientifica: 'FEDEARROZ - Manejo agronómico arroz.',
  },
  {
    codigo: 'R-ARRZ-009',
    nombre: 'Manejo socas arroz post-cosecha',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Arroz',
    faseAgronomica: 'post_cosecha',
    accionSugerida:
      'Eliminar socas (rastrojos) para romper ciclo de plagas. PREFERIBLE: incorporación con disco al suelo (más sostenible que quema).',
    prioridad: 3,
    fuenteCientifica: 'FEDEARROZ - Manejo socas.',
  },
];
