import { ReglaSeed } from './index';

/**
 * 15 reglas Sorgo, Pastos, Hortalizas - Sprint 4 AgroField
 * Fuentes: AGROSAVIA Cesar, Fedegán, ICA, Plantix, Infoagro
 */
export const reglasSorgoPastosHortalizas: ReglaSeed[] = [
  // ─── SORGO ─────────
  {
    codigo: 'R-SORG-001',
    nombre: 'Mosca midge sorgo en floración',
    descripcion: 'Pérdidas hasta 100% en floración sin control.',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Sorgo',
    plagaNombre: 'Mosca midge',
    faseAgronomica: 'floracion',
    severidadMinima: 'media',
    accionSugerida:
      'Insecticida cuando se observen primeros adultos en panoja. Monitoreo crítico al amanecer.',
    productoSugerido: 'Lambda-cyhalothrin o Methomyl',
    dosisRecomendada: 200,
    unidadRecomendada: 'cc/ha',
    metodoAplicacion: 'aspersion_dirigida_panoja',
    frecuenciaDias: 6,
    prioridad: 5,
    fuenteCientifica: 'AGROSAVIA - Manejo mosca ovario sorgo. Panorama Agrario.',
  },
  {
    codigo: 'R-SORG-002',
    nombre: 'Pulgón amarillo sorgo',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Sorgo',
    plagaNombre: 'Pulgones',
    severidadMinima: 'media',
    accionSugerida: 'Monitoreo desde V3. Umbral: 20% plantas con ≥50 pulgones/hoja.',
    productoSugerido: 'Sulfoxaflor o Flupyradifurone',
    dosisRecomendada: 200,
    unidadRecomendada: 'cc/ha',
    metodoAplicacion: 'aspersion_foliar',
    prioridad: 4,
    fuenteCientifica: 'AGROSAVIA Cesar - Plagas sorgo forrajero. AgroSpray.',
  },
  {
    codigo: 'R-SORG-003',
    nombre: 'Ergot del sorgo (Claviceps africana)',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Sorgo',
    faseAgronomica: 'floracion',
    severidadMinima: 'media',
    accionSugerida:
      'Arar residuos de campo. Rotar cultivos cada 3 años. Aplicar fungicida durante floración si HR alta y T ~20°C.',
    productoSugerido: 'Tebuconazol',
    dosisRecomendada: 0.5,
    unidadRecomendada: 'L/ha',
    metodoAplicacion: 'aspersion_dirigida_panoja',
    prioridad: 4,
    fuenteCientifica: 'Plantix - Ergot del sorgo.',
  },
  {
    codigo: 'R-SORG-004',
    nombre: 'Rotación sorgo con leguminosa',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Sorgo',
    faseAgronomica: 'post_cosecha',
    accionSugerida:
      'Rotar sorgo con leguminosa (frijol caupí, mucuna) para fijar nitrógeno y romper ciclos de plagas.',
    prioridad: 3,
    fuenteCientifica: 'AGROSAVIA - Sistemas productivos Cesar.',
  },
  {
    codigo: 'R-SORG-005',
    nombre: 'Gusano cogollero sorgo',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Sorgo',
    plagaNombre: 'Gusano cogollero',
    severidadMinima: 'media',
    accionSugerida: 'Mismo manejo que en maíz. Insecticida sobre cogollo con larvas pequeñas.',
    productoSugerido: 'Clorantraniliprole',
    dosisRecomendada: 200,
    unidadRecomendada: 'cc/ha',
    metodoAplicacion: 'aspersion_dirigida_cogollo',
    prioridad: 4,
    fuenteCientifica: 'AGROSAVIA - Plagas sorgo forrajero Caribe Seco.',
  },
  // ─── PASTO ANGLETON ─────────
  {
    codigo: 'R-PAST-001',
    nombre: 'Mión de los pastos Angleton (salivazo)',
    descripcion: 'Plaga más compleja del Caribe en lluvias.',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Pasto Angleton',
    plagaNombre: 'Mión de los pastos',
    estacion: 'lluviosa',
    severidadMinima: 'media',
    accionSugerida:
      'Rotación de potreros con descanso ≤24 días. Pastoreo dirigido. Productos biológicos con Beauveria + Metarhizium.',
    productoSugerido: 'Beauveria + Metarhizium anisopliae',
    dosisRecomendada: 2,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_+_cultural',
    frecuenciaDias: 8,
    prioridad: 5,
    fuenteCientifica: 'Fedegán - Angletón enfermedades plagas. Invesa Salivazo.',
  },
  {
    codigo: 'R-PAST-002',
    nombre: 'Pulgón pastos Angleton/Brachiaria',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Pasto Angleton',
    plagaNombre: 'Pulgones',
    estacion: 'transicion',
    severidadMinima: 'media',
    accionSugerida:
      'Insecticida selectivo si daño económico evidente. Lluvias intensas suelen eliminar al pulgón.',
    productoSugerido: 'Imidacloprid',
    dosisRecomendada: 200,
    unidadRecomendada: 'cc/ha',
    metodoAplicacion: 'aspersion_foliar',
    prioridad: 3,
    fuenteCientifica: 'CONtexto Ganadero - Pulgón pastos Bolívar y Cesar.',
  },
  {
    codigo: 'R-PAST-003',
    nombre: 'Carbón espiga Angleton',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Pasto Angleton',
    severidadMinima: 'media',
    accionSugerida:
      'Usar semilla certificada tratada con fungicida. No hay control curativo en campo.',
    productoSugerido: 'Carboxin (tratamiento semilla)',
    metodoAplicacion: 'tratamiento_semilla',
    prioridad: 3,
    fuenteCientifica: 'CONtexto Ganadero - Enfermedades Angletón.',
  },
  {
    codigo: 'R-PAST-004',
    nombre: 'Rotación potreros Angleton 24-30 días',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Pasto Angleton',
    accionSugerida:
      'Rotación con descanso 24-30 días entre pastoreos. Carga 1-1.5 UGG/ha. Resembrar zonas degradadas cada 5 años.',
    frecuenciaDias: 27,
    prioridad: 4,
    fuenteCientifica: 'Fedegán - Manejo pasto Angleton trópico bajo.',
  },
  {
    codigo: 'R-PAST-005',
    nombre: 'Chinches pastos (Blissus, Collaria)',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Pasto Angleton',
    plagaNombre: 'Chinche de los pastos',
    severidadMinima: 'media',
    accionSugerida:
      'Liberar Chrysoperla (20-60 mil larvas/ha). Control biológico con Bacillus thuringiensis, Beauveria, Paecilomyces.',
    productoSugerido: 'Bacillus thuringiensis + Beauveria',
    dosisRecomendada: 2,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'biologico',
    frecuenciaDias: 8,
    prioridad: 4,
    fuenteCientifica: 'CONtexto Ganadero - Artrópodos herbívoros pasturas SSPi.',
  },
  // ─── HORTALIZAS ─────────
  {
    codigo: 'R-HORT-001',
    nombre: 'Tuta absoluta tomate (>50% pérdidas)',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Tomate',
    plagaNombre: 'Tuta absoluta',
    severidadMinima: 'media',
    accionSugerida:
      'Trampas con feromonas para detección precoz. Liberación de Trichogramma + Bacillus thuringiensis. Rotar productos para evitar resistencia.',
    productoSugerido: 'Spinosad o Clorantraniliprole + Bt',
    dosisRecomendada: 0.3,
    unidadRecomendada: 'L/ha',
    metodoAplicacion: 'aspersion_foliar_+_biologico',
    frecuenciaDias: 30,
    prioridad: 5,
    fuenteCientifica: 'AGROSAVIA proinv728 - Manejo integrado Tuta absoluta. Agronegocios 2023.',
  },
  {
    codigo: 'R-HORT-002',
    nombre: 'Marchitez bacteriana solanáceas (Ralstonia)',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Tomate',
    severidadMinima: 'baja',
    accionSugerida:
      'NO hay control curativo. Erradicar plantas. Rotación con gramíneas mínimo 4 años. Hipoclorito 1% para desinfección herramientas.',
    productoSugerido: 'Hipoclorito al 1%',
    metodoAplicacion: 'cultural_+_erradicacion',
    prioridad: 5,
    fuenteCientifica: 'ICA - Manejo Ralstonia solanaceae.',
  },
  {
    codigo: 'R-HORT-003',
    nombre: 'Tizón tardío tomate',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Tomate',
    severidadMinima: 'media',
    estacion: 'lluviosa',
    accionSugerida: 'Fungicida preventivo. Eliminar follaje afectado. Variedades resistentes.',
    productoSugerido: 'Metalaxil + Mancozeb',
    dosisRecomendada: 2.5,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_foliar',
    frecuenciaDias: 7,
    prioridad: 5,
    fuenteCientifica: 'ICA - Manejo tizón solanáceas.',
  },
  {
    codigo: 'R-HORT-004',
    nombre: 'Solarización suelo invernadero',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Tomate',
    faseAgronomica: 'preparacion',
    estacion: 'seca',
    accionSugerida:
      'Cubrir suelo con plástico transparente 4-5 semanas en seca. Elimina crisálidas Tuta, nematodos, hongos del suelo y semillas de malezas.',
    prioridad: 4,
    fuenteCientifica: 'Infoagro - Solarización invernaderos Tuta.',
  },
  {
    codigo: 'R-HORT-005',
    nombre: 'Mallas anti-insecto invernaderos',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Tomate',
    accionSugerida:
      'Instalar mallas con apertura <1.6 mm en aberturas. Doble puerta. Impide entrada de Tuta absoluta, mosca blanca, trips.',
    prioridad: 4,
    fuenteCientifica: 'Infoagro - Manejo cultural Tuta absoluta.',
  },
];
