import { ReglaSeed } from './index';

/**
 * 10 reglas Frijol caupí (Vigna unguiculata) - Sprint 4 AgroField
 * Fuentes: CIAT, AGROSAVIA Caribe Seco, INIFAP
 */
export const reglasFrijol: ReglaSeed[] = [
  {
    codigo: 'R-FRIJ-001',
    nombre: 'Lorito verde frijol (Empoasca kraemeri)',
    descripcion: 'Plaga más frecuente en Caribe Seco colombiano.',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Frijol',
    plagaNombre: 'Pulgones',
    severidadMinima: 'media',
    accionSugerida:
      'Insecticida sistémico. Promover Orius insidiosus (depredador). Rotar productos para evitar resistencia.',
    productoSugerido: 'Imidacloprid o Thiamethoxam',
    dosisRecomendada: 250,
    unidadRecomendada: 'cc/ha',
    metodoAplicacion: 'aspersion_foliar',
    prioridad: 4,
    fuenteCientifica: 'CIAT - Guía enfermedades y plagas del frijol Colombia.',
  },
  {
    codigo: 'R-FRIJ-002',
    nombre: 'Diabrótica del frijol',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Frijol',
    severidadMinima: 'media',
    accionSugerida:
      'Monitoreo con trampas amarillas pegajosas. Aplicar insecticida si supera 5 adultos/planta.',
    productoSugerido: 'Lambda-cyhalothrin',
    dosisRecomendada: 200,
    unidadRecomendada: 'cc/ha',
    metodoAplicacion: 'aspersion_foliar',
    prioridad: 3,
    fuenteCientifica: 'CIAT - Plagas frijol Colombia.',
  },
  {
    codigo: 'R-FRIJ-003',
    nombre: 'Mancha angular frijol (Phaseoisariopsis griseola)',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Frijol',
    plagaNombre: 'Mancha angular',
    severidadMinima: 'media',
    estacion: 'lluviosa',
    accionSugerida: 'Fungicida sistémico. Eliminar restos vegetales y rotar cultivos.',
    productoSugerido: 'Azoxistrobina + Difenoconazol',
    dosisRecomendada: 0.5,
    unidadRecomendada: 'L/ha',
    metodoAplicacion: 'aspersion_foliar',
    frecuenciaDias: 14,
    prioridad: 4,
    fuenteCientifica: 'CIAT - Cartilla Jara y Cotes 2016 manejo agronómico frijol.',
  },
  {
    codigo: 'R-FRIJ-004',
    nombre: 'Roya del frijol (Uromyces appendiculatus)',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Frijol',
    plagaNombre: 'Roya del frijol',
    severidadMinima: 'media',
    accionSugerida: 'Fungicida sistémico. Variedades resistentes preferibles.',
    productoSugerido: 'Tebuconazol',
    dosisRecomendada: 0.5,
    unidadRecomendada: 'L/ha',
    metodoAplicacion: 'aspersion_foliar',
    prioridad: 4,
    fuenteCientifica: 'CIAT - Enfermedades frijol Colombia.',
  },
  {
    codigo: 'R-FRIJ-005',
    nombre: 'Antracnosis frijol (Colletotrichum lindemuthianum)',
    descripcion: 'Probablemente la enfermedad más importante del frijol en Colombia.',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Frijol',
    plagaNombre: 'Antracnosis',
    severidadMinima: 'alta',
    accionSugerida:
      'Usar semilla sana. Fungicidas: clorotalonil, mancozeb o azoxistrobina. Eliminar restos de cultivo.',
    productoSugerido: 'Clorotalonil',
    dosisRecomendada: 2.5,
    unidadRecomendada: 'L/ha',
    metodoAplicacion: 'aspersion_foliar',
    frecuenciaDias: 10,
    prioridad: 5,
    fuenteCientifica: 'CIAT - Guía enfermedades frijol Colombia.',
  },
  {
    codigo: 'R-FRIJ-006',
    nombre: 'Tizón común frijol (Xanthomonas)',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Frijol',
    severidadMinima: 'media',
    accionSugerida: 'Bactericida cúprico. Usar semilla certificada. Evitar siembras escalonadas.',
    productoSugerido: 'Hidróxido de cobre',
    dosisRecomendada: 3,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_foliar',
    prioridad: 3,
    fuenteCientifica: 'INIFAP-CIAT - Manejo integrado frijol.',
  },
  {
    codigo: 'R-FRIJ-007',
    nombre: 'Pudriciones de raíz frijol',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Frijol',
    severidadMinima: 'media',
    accionSugerida:
      'Mejorar drenaje. Rotación con gramíneas. Tratamiento de semilla con Trichoderma.',
    productoSugerido: 'Trichoderma harzianum (tratamiento semilla)',
    metodoAplicacion: 'tratamiento_semilla_+_drenaje',
    prioridad: 3,
    fuenteCientifica: 'INIFAP-CIAT - Pudriciones de raíz frijol.',
  },
  {
    codigo: 'R-FRIJ-008',
    nombre: 'Densidad frijol caupí Caribe Seco',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Frijol',
    faseAgronomica: 'preparacion',
    accionSugerida:
      'Densidad 80000-100000 plantas/ha. Distancia: 0.6 m entre surcos, 0.15 m entre plantas. Frijol caupí tolera condiciones secas.',
    dosisRecomendada: 90000,
    unidadRecomendada: 'plantas/ha',
    prioridad: 3,
    fuenteCientifica: 'AGROSAVIA Caribe Seco - Manejo frijol caupí.',
  },
  {
    codigo: 'R-FRIJ-009',
    nombre: 'Fertilización P-K frijol (leguminosa)',
    descripcion: 'Frijol fija nitrógeno, no requiere mucho N.',
    tipoRecomendacion: 'fertilizacion',
    cultivoNombre: 'Frijol',
    faseAgronomica: 'siembra',
    accionSugerida:
      'Aplicar principalmente fósforo y potasio. Evitar exceso de N que reduce fijación simbiótica.',
    productoSugerido: 'DAP + KCl',
    dosisRecomendada: 150,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'edafica',
    prioridad: 3,
    fuenteCientifica: 'CIAT - Fertilización frijol Caribe.',
  },
  {
    codigo: 'R-FRIJ-010',
    nombre: 'Inoculación Rhizobium pre-siembra',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Frijol',
    faseAgronomica: 'siembra',
    accionSugerida:
      'Inocular semilla con Rhizobium phaseoli antes de siembra. Incrementa fijación de nitrógeno hasta 80 kg N/ha.',
    productoSugerido: 'Rhizobium phaseoli',
    dosisRecomendada: 200,
    unidadRecomendada: 'g/100 kg semilla',
    metodoAplicacion: 'tratamiento_semilla',
    prioridad: 4,
    fuenteCientifica: 'CIAT - Inoculantes biológicos frijol.',
  },
];
