import { ReglaSeed } from './index';

/**
 * 8 reglas Aguacate Hass (Persea americana) - Sprint 4 AgroField
 * Fuentes: ICA, AGROSAVIA, Tamayo
 */
export const reglasAguacate: ReglaSeed[] = [
  {
    codigo: 'R-AGUA-001',
    nombre: 'Pudrición radical aguacate (Phytophthora cinnamomi)',
    descripcion: 'Enfermedad más importante del aguacate en el mundo.',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Aguacate',
    plagaNombre: 'Phytophthora cinnamomi',
    severidadMinima: 'media',
    accionSugerida:
      'Inyección de fosfitos al tronco. Mejorar drenaje. NO hay erradicación una vez infectado. Prevención y mitigación.',
    productoSugerido: 'Fosfito de potasio (inyección tronco)',
    dosisRecomendada: 25,
    unidadRecomendada: 'mL/árbol',
    metodoAplicacion: 'inyeccion_tronco',
    frecuenciaDias: 90,
    prioridad: 5,
    fuenteCientifica: 'ICA - Boletín Phytophthora cinnamomi aguacate. AGROSAVIA Tamayo 2014.',
  },
  {
    codigo: 'R-AGUA-002',
    nombre: 'Marchitez Verticillium aguacate',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Aguacate',
    plagaNombre: 'Verticillium',
    severidadMinima: 'alta',
    accionSugerida:
      'NO hay control químico. Eliminar árboles afectados. Solarización del suelo. Usar patrones resistentes.',
    metodoAplicacion: 'erradicacion_+_cultural',
    prioridad: 5,
    fuenteCientifica: 'AGROSAVIA - Marchitez aguacate Antioquia.',
  },
  {
    codigo: 'R-AGUA-003',
    nombre: 'Patrón Antillano para Caribe cálido',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Aguacate',
    faseAgronomica: 'preparacion',
    accionSugerida:
      'En zonas cálidas del Caribe usar patrón Antillano (tolerante a calor y salinidad), no Mexicano. Injertar Hass sobre Antillano.',
    prioridad: 3,
    fuenteCientifica: 'AGROSAVIA - Aguacate Montes de María.',
  },
  {
    codigo: 'R-AGUA-004',
    nombre: 'Riego floración-cuajado aguacate',
    tipoRecomendacion: 'riego',
    cultivoNombre: 'Aguacate',
    faseAgronomica: 'floracion',
    diasSinRiegoMinimo: 5,
    accionSugerida: 'Riego abundante en floración y cuajado. Déficit causa caída masiva de frutos.',
    dosisRecomendada: 120,
    unidadRecomendada: 'L/árbol/semana',
    metodoAplicacion: 'goteo',
    frecuenciaDias: 7,
    prioridad: 5,
    fuenteCientifica: 'ICA - Requerimientos hídricos aguacate.',
  },
  {
    codigo: 'R-AGUA-005',
    nombre: 'Aguacate fertilización potasio alto',
    tipoRecomendacion: 'fertilizacion',
    cultivoNombre: 'Aguacate',
    faseAgronomica: 'fructificacion',
    accionSugerida:
      'Aplicar fertilización rica en potasio durante llenado de fruto. Aguacate extrae ~3.5 kg K por tonelada producida.',
    productoSugerido: 'Sulfato de potasio o KNO3',
    dosisRecomendada: 1.5,
    unidadRecomendada: 'kg/árbol',
    metodoAplicacion: 'edafica',
    frecuenciaDias: 90,
    prioridad: 4,
    fuenteCientifica: 'ICA - Nutrición aguacate Colombia.',
  },
  {
    codigo: 'R-AGUA-006',
    nombre: 'Trips aguacate (Frankliniella)',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Aguacate',
    plagaNombre: 'Trips',
    severidadMinima: 'media',
    accionSugerida: 'Liberación de Orius. Si supera umbral, aplicación de Spinosad.',
    productoSugerido: 'Spinosad',
    dosisRecomendada: 0.3,
    unidadRecomendada: 'L/ha',
    metodoAplicacion: 'biologico_+_selectivo',
    prioridad: 3,
    fuenteCientifica: 'AGROSAVIA - Trips aguacate.',
  },
  {
    codigo: 'R-AGUA-007',
    nombre: 'Antracnosis frutos aguacate post-cosecha',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Aguacate',
    plagaNombre: 'Antracnosis',
    faseAgronomica: 'fructificacion',
    severidadMinima: 'media',
    accionSugerida:
      'Aplicación preventiva en pre-cosecha. Termoterapia post-cosecha (49°C × 10 min reduce antracnosis).',
    productoSugerido: 'Procloraz',
    dosisRecomendada: 0.5,
    unidadRecomendada: 'cc/L',
    metodoAplicacion: 'aspersion_foliar_+_termoterapia',
    prioridad: 4,
    fuenteCientifica: 'Asohofrucol - Antracnosis frutales Colombia.',
  },
  {
    codigo: 'R-AGUA-008',
    nombre: 'Asfixia radicular aguacate (drenaje crítico)',
    tipoRecomendacion: 'manejo_cultural',
    cultivoNombre: 'Aguacate',
    estacion: 'lluviosa',
    accionSugerida:
      'Drenaje crítico. Aguacate no tolera encharcamiento >24h. Sembrar en camas elevadas en zonas con riesgo de inundación.',
    prioridad: 5,
    fuenteCientifica: 'AGROSAVIA Tamayo - Marchitez aguacate factores abióticos.',
  },
];
