import { ReglaSeed } from './index';

/**
 * 10 reglas de ENFERMEDADES (hongos/bacterias/virus) - Sprint 4 AgroField
 * Fuentes: AGROSAVIA, CENICAFE, CENIPALMA, ICA, Acorbat, Anacafe
 */
export const reglasEnfermedades: ReglaSeed[] = [
  {
    codigo: 'R-ENF-001',
    nombre: 'Pudricion radicular yuca',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Yuca',
    severidadMinima: 'media',
    accionSugerida:
      'Mejorar drenaje del suelo. Aplicar Trichoderma harzianum. Sembrar variedad tolerante.',
    productoSugerido: 'Trichoderma harzianum',
    dosisRecomendada: 2.5,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'edafica',
    prioridad: 4,
    fuenteCientifica: 'AGROSAVIA - Enfermedades yuca control biologico.',
  },
  {
    codigo: 'R-ENF-002',
    nombre: 'Mancha de hierro cafe',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Café',
    severidadMinima: 'media',
    accionSugerida:
      'Mejorar nutricion (especialmente N), reducir sombrio excesivo. Aplicar fungicida si severo.',
    productoSugerido: 'Opus 12.5 SC',
    dosisRecomendada: 0.6,
    unidadRecomendada: 'L/ha',
    metodoAplicacion: 'aspersion_foliar',
    prioridad: 3,
    fuenteCientifica: 'CENICAFE / BASF Opus mancha de hierro.',
  },
  {
    codigo: 'R-ENF-003',
    nombre: 'Llagas radicales cafe (sin fungicida)',
    descripcion: 'NO aplicar fungicida curativo. Eliminar plantas + encalar.',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Café',
    severidadMinima: 'baja',
    accionSugerida:
      'NO aplicar fungicida curativo. Eliminar y remover plantas afectadas con raices. Encalar el hoyo.',
    productoSugerido: 'Cal agricola',
    dosisRecomendada: 2.5,
    unidadRecomendada: 'kg/sitio',
    metodoAplicacion: 'edafica_localizada',
    prioridad: 5,
    fuenteCientifica: 'CENICAFE - Manejo de enfermedades cafe (cultivemos_cafe).',
  },
  {
    codigo: 'R-ENF-004',
    nombre: 'Muerte descendente cafe (Phoma)',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Café',
    severidadMinima: 'media',
    accionSugerida:
      'Aplicar Captan 80WG en almacigos y zonas criticas. Proteger de corrientes frias.',
    productoSugerido: 'Captan 80WG o Carbendazim (Derosal)',
    dosisRecomendada: 4,
    unidadRecomendada: 'g/L de agua',
    metodoAplicacion: 'aspersion_foliar',
    prioridad: 3,
    fuenteCientifica: 'CENICAFE - Manejo Phoma cafe.',
  },
  {
    codigo: 'R-ENF-005',
    nombre: 'Pudricion del pie en papaya/cucurbitaceas',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    severidadMinima: 'baja',
    accionSugerida: 'Mejorar drenaje. Aplicar Metalaxil al suelo. Sembrar en camas elevadas.',
    productoSugerido: 'Metalaxil o Fosetil-Al',
    dosisRecomendada: 2.5,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'drench_al_cuello',
    prioridad: 5,
    fuenteCientifica: 'AGROSAVIA - Papaya control plagas y enfermedades.',
  },
  {
    codigo: 'R-ENF-006',
    nombre: 'Antracnosis cafe (Colletotrichum)',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Café',
    plagaNombre: 'Antracnosis',
    faseAgronomica: 'floracion',
    severidadMinima: 'media',
    accionSugerida: 'Aplicar fungicida cuprico preventivo en floracion y cuajado.',
    productoSugerido: 'Oxicloruro de cobre o Hidroxido de cobre',
    dosisRecomendada: 3,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_foliar',
    prioridad: 3,
    fuenteCientifica: 'Anacafe - Manejo Colletotrichum cafe 2016-2021.',
  },
  {
    codigo: 'R-ENF-007',
    nombre: 'Sigatoka amarilla banano (presion menor)',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Banano',
    severidadMinima: 'baja',
    accionSugerida:
      'Igual manejo que sigatoka negra pero con menor presion. Programa preventivo de fungicidas sistemicos.',
    productoSugerido: 'Mancozeb o Tridemorf',
    dosisRecomendada: 1.75,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_foliar',
    frecuenciaDias: 14,
    prioridad: 3,
    fuenteCientifica: 'Acorbat - Manejo sigatoka amarilla banano.',
  },
  {
    codigo: 'R-ENF-008',
    nombre: 'Marchitez bacteriana solanaceas (sin cura)',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    severidadMinima: 'baja',
    accionSugerida:
      'No hay control curativo. Erradicar plantas. Rotacion con gramineas. Desinfectar herramientas con hipoclorito 1%.',
    productoSugerido: 'Hipoclorito al 1% (desinfeccion herramientas)',
    metodoAplicacion: 'cultural_+_erradicacion',
    prioridad: 5,
    fuenteCientifica: 'ICA - Manejo Ralstonia solanaceae.',
  },
  {
    codigo: 'R-ENF-009',
    nombre: 'Pudricion cogollo palma (PC - control oficial)',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Palma de aceite',
    severidadMinima: 'baja',
    accionSugerida:
      'ALERTA: Plaga de control oficial (Resolucion ICA 092771/2021). Aplicar cirugia agronomica si sintomas tempranos. Reportar al ICA.',
    productoSugerido: 'Metalaxil + Cirugia',
    metodoAplicacion: 'mecanico_+_quimico_localizado',
    prioridad: 5,
    fuenteCientifica: 'Cenipalma. Resolucion ICA 092771/2021.',
  },
  {
    codigo: 'R-ENF-010',
    nombre: 'Marchitez letal palma (ML - cuarentenaria)',
    tipoRecomendacion: 'fitosanitario_enfermedad',
    cultivoNombre: 'Palma de aceite',
    severidadMinima: 'baja',
    accionSugerida:
      'ALERTA: enfermedad cuarentenaria. Reportar al ICA. Erradicar palmas afectadas. Control de Myndus crudus (vector).',
    metodoAplicacion: 'erradicacion_+_control_vector',
    prioridad: 5,
    fuenteCientifica: 'Resolucion ICA 092771/2021 - Plaga control oficial.',
  },
];
