import { ReglaSeed } from './index';

/**
 * 10 reglas de FERTILIZACION - Sprint 4 AgroField
 * Fuentes: INIAP, AGROES, Fertilab, AGROSAVIA, FAO, Wikifarmer, Risso
 */
export const reglasFertilizacion: ReglaSeed[] = [
  {
    codigo: 'R-FERT-001',
    nombre: 'Banano fertilizacion mensual con riego',
    descripcion: 'Plan anual: 16-18 sacos urea/ha/ano + muriato de potasio + DAP + Sulpomag.',
    tipoRecomendacion: 'fertilizacion',
    cultivoNombre: 'Banano',
    accionSugerida:
      'Aplicar plan anual: 16-18 sacos urea/ha/ano, 18-20 sacos muriato de potasio/ha/ano, 2-4 sacos DAP/ha/ano, 2-4 sacos Sulpomag/ha/ano. Distribuir en 12 aplicaciones.',
    productoSugerido: 'Urea (46-0-0) + Muriato potasio + DAP',
    dosisRecomendada: 70,
    unidadRecomendada: 'kg urea/ha/aplicacion',
    metodoAplicacion: 'edafica',
    frecuenciaDias: 30,
    prioridad: 3,
    fuenteCientifica:
      'INIAP - Programa nutricion banano. Wikifarmer - Necesidades nutrientes banano.',
  },
  {
    codigo: 'R-FERT-002',
    nombre: 'Banano sin riego: 3 aplicaciones anuales',
    descripcion: 'Aplicar coincidiendo con lluvias del Magdalena.',
    tipoRecomendacion: 'fertilizacion',
    cultivoNombre: 'Banano',
    accionSugerida:
      'Aplicar fertilizacion fraccionada en 3 momentos coincidentes con lluvias del Magdalena (Dic-Ene, May-Jun, Oct-Nov).',
    productoSugerido: 'Formula 8-10-8 NPK',
    dosisRecomendada: 350,
    unidadRecomendada: 'g/planta/aplicacion',
    metodoAplicacion: 'edafica',
    prioridad: 3,
    fuenteCientifica: 'INIAP - Nutricion banano sin riego.',
  },
  {
    codigo: 'R-FERT-003',
    nombre: 'Maiz fertilizacion de fondo en siembra',
    tipoRecomendacion: 'fertilizacion',
    cultivoNombre: 'Maíz',
    faseAgronomica: 'siembra',
    diasDesdeSiembraMaximo: 7,
    accionSugerida:
      'Aplicar fertilizacion de fondo. En suelos con fosforo alto: 800 kg/ha NPK 12-10-17.',
    productoSugerido: 'NPK 12-10-17 o NPK 15-15-15',
    dosisRecomendada: 250,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'edafica',
    prioridad: 4,
    fuenteCientifica: 'Fertilab Mexico - Manejo fertilizacion maiz. Infoagro NPK dosis maiz.',
  },
  {
    codigo: 'R-FERT-004',
    nombre: 'Maiz primera cobertera (40 cm altura)',
    tipoRecomendacion: 'fertilizacion',
    cultivoNombre: 'Maíz',
    faseAgronomica: 'crecimiento_vegetativo',
    diasDesdeSiembraMinimo: 25,
    diasDesdeSiembraMaximo: 35,
    accionSugerida: 'Aplicar urea como primera cobertera cuando la planta tenga ~40 cm de altura.',
    productoSugerido: 'Urea 46%',
    dosisRecomendada: 225,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'edafica',
    prioridad: 4,
    fuenteCientifica: 'AGROES - Abonado del maiz.',
  },
  {
    codigo: 'R-FERT-005',
    nombre: 'Maiz segunda cobertera (pre-floracion)',
    tipoRecomendacion: 'fertilizacion',
    cultivoNombre: 'Maíz',
    faseAgronomica: 'pre_floracion',
    diasDesdeSiembraMinimo: 50,
    diasDesdeSiembraMaximo: 65,
    accionSugerida:
      'Aplicar segunda cobertera nitrogenada antes de floracion. Usar NAC 27 o nitrosulfato amonico 26.',
    productoSugerido: 'NAC 27 o Urea',
    dosisRecomendada: 300,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'edafica',
    prioridad: 4,
    fuenteCientifica: 'AGROES - Abonado del maiz fraccionado.',
  },
  {
    codigo: 'R-FERT-006',
    nombre: 'Arroz NPK base en siembra',
    tipoRecomendacion: 'fertilizacion',
    cultivoNombre: 'Arroz',
    faseAgronomica: 'siembra',
    diasDesdeSiembraMaximo: 10,
    accionSugerida: 'Aplicar NPK complementado con micronutrientes para incrementar rendimiento.',
    productoSugerido: 'NPK 15-15-15',
    dosisRecomendada: 300,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'voleo',
    prioridad: 4,
    fuenteCientifica: 'Cedeno-Duenas et al. (2018) - Fertilizacion NPK arroz.',
  },
  {
    codigo: 'R-FERT-007',
    nombre: 'Arroz nitrogeno fraccionado en macollamiento',
    tipoRecomendacion: 'fertilizacion',
    cultivoNombre: 'Arroz',
    faseAgronomica: 'crecimiento_vegetativo',
    diasDesdeSiembraMinimo: 20,
    diasDesdeSiembraMaximo: 45,
    accionSugerida:
      'Aplicar urea fraccionada en 3 momentos: macollamiento, inicio primordial floral, y paniculas en barriga.',
    productoSugerido: 'Urea 46%',
    dosisRecomendada: 180,
    unidadRecomendada: 'kg/ha total fraccionada',
    metodoAplicacion: 'edafica',
    frecuenciaDias: 12,
    prioridad: 4,
    fuenteCientifica: 'Risso - Metodos de aplicacion de urea cultivos de grano.',
  },
  {
    codigo: 'R-FERT-008',
    nombre: 'Yuca fertilizacion moderada NPK',
    tipoRecomendacion: 'fertilizacion',
    cultivoNombre: 'Yuca',
    faseAgronomica: 'crecimiento_vegetativo',
    diasDesdeSiembraMinimo: 30,
    diasDesdeSiembraMaximo: 60,
    accionSugerida:
      'Aplicar fertilizacion moderada. La yuca es tolerante a suelos pobres pero responde a NPK balanceado.',
    productoSugerido: 'NPK 10-20-20 o 15-15-15',
    dosisRecomendada: 175,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'edafica',
    prioridad: 3,
    fuenteCientifica: 'AGROSAVIA - Manual yuca industrial Caribe.',
  },
  {
    codigo: 'R-FERT-009',
    nombre: 'Cafe fertilizacion post-cosecha',
    tipoRecomendacion: 'fertilizacion',
    cultivoNombre: 'Café',
    faseAgronomica: 'post_cosecha',
    accionSugerida: 'Reponer nutrientes extraidos. Aplicar formula completa.',
    productoSugerido: 'NPK 17-6-18-2 o DAP + KCl',
    dosisRecomendada: 175,
    unidadRecomendada: 'g/planta',
    metodoAplicacion: 'edafica',
    prioridad: 3,
    fuenteCientifica: 'CENICAFE - Manejo fertilizacion cafetales.',
  },
  {
    codigo: 'R-FERT-010',
    nombre: 'Mango pre-floracion: K y P, reducir N',
    tipoRecomendacion: 'fertilizacion',
    cultivoNombre: 'Mango',
    faseAgronomica: 'pre_floracion',
    accionSugerida:
      'Aplicar fertilizacion con potasio y fosforo, reducir nitrogeno para no estimular vegetativo.',
    productoSugerido: 'Sulfato de potasio + DAP',
    dosisRecomendada: 1.5,
    unidadRecomendada: 'kg/arbol',
    metodoAplicacion: 'edafica',
    prioridad: 3,
    fuenteCientifica: 'FAO mango Magdalena.',
  },
];
