import { ReglaSeed } from './index';

/**
 * 10 reglas de RIEGO - Sprint 4 AgroField
 * Fuentes: FAO, CROPWAT, AGROSAVIA, CENICAFE, CENIPALMA, FONTAGRO
 */
export const reglasRiego: ReglaSeed[] = [
  {
    codigo: 'R-RIEGO-001',
    nombre: 'Banano sin riego prolongado en estacion seca',
    descripcion: 'El banano es altamente sensible al deficit hidrico en cualquier fase.',
    tipoRecomendacion: 'riego',
    cultivoNombre: 'Banano',
    faseAgronomica: 'crecimiento_vegetativo',
    estacion: 'seca',
    diasSinRiegoMinimo: 3,
    accionSugerida:
      'Aplicar riego inmediato. El banano es altamente sensible al deficit hidrico en cualquier fase.',
    dosisRecomendada: 35,
    unidadRecomendada: 'L/planta/dia',
    metodoAplicacion: 'goteo',
    prioridad: 5,
    fuenteCientifica:
      'FAO (2018) - Requerimientos hidricos del cultivo de banano y platano. Fontagro.',
  },
  {
    codigo: 'R-RIEGO-002',
    nombre: 'Platano sin riego en floracion',
    descripcion: 'Estres hidrico durante floracion reduce rendimiento >30%.',
    tipoRecomendacion: 'riego',
    cultivoNombre: 'Plátano',
    faseAgronomica: 'floracion',
    diasSinRiegoMinimo: 2,
    accionSugerida:
      'Riego urgente durante floracion. Estres hidrico en esta fase reduce rendimiento >30%.',
    dosisRecomendada: 30,
    unidadRecomendada: 'L/planta/dia',
    metodoAplicacion: 'goteo',
    prioridad: 5,
    fuenteCientifica:
      'Cigales & Perez (2011) - Estimacion CROPWAT necesidades hidricas banano y platano.',
  },
  {
    codigo: 'R-RIEGO-003',
    nombre: 'Maiz floracion sin riego (fase critica)',
    descripcion: 'El estres hidrico entre VT (panoja) y R1 (antesis) reduce drasticamente granos.',
    tipoRecomendacion: 'riego',
    cultivoNombre: 'Maíz',
    faseAgronomica: 'floracion',
    diasSinRiegoMinimo: 4,
    accionSugerida:
      'Riego de emergencia. El estres hidrico entre VT (panoja) y R1 (antesis) reduce drasticamente el numero de granos.',
    dosisRecomendada: 60,
    unidadRecomendada: 'mm/aplicacion',
    metodoAplicacion: 'aspersion',
    prioridad: 5,
    fuenteCientifica: 'FAO (2016) - Etapas fenologicas criticas del maiz, evapotranspiracion.',
  },
  {
    codigo: 'R-RIEGO-004',
    nombre: 'Maiz fase vegetativa moderada sin riego',
    tipoRecomendacion: 'riego',
    cultivoNombre: 'Maíz',
    faseAgronomica: 'crecimiento_vegetativo',
    estacion: 'seca',
    diasSinRiegoMinimo: 7,
    accionSugerida: 'Programar riego para mantener crecimiento foliar.',
    dosisRecomendada: 40,
    unidadRecomendada: 'mm/aplicacion',
    metodoAplicacion: 'aspersion',
    prioridad: 3,
    fuenteCientifica: 'FAO CROPWAT - Requerimientos hidricos cereales.',
  },
  {
    codigo: 'R-RIEGO-005',
    nombre: 'Arroz mantener lamina permanente',
    descripcion: 'Mantener lamina de agua de 5-10 cm en arroz inundado.',
    tipoRecomendacion: 'riego',
    cultivoNombre: 'Arroz',
    faseAgronomica: 'crecimiento_vegetativo',
    estacion: 'seca',
    diasSinRiegoMinimo: 1,
    accionSugerida:
      'Mantener lamina de agua de 5-10 cm en arroz inundado. Reponer al menos cada 2-3 dias en arroz secano.',
    dosisRecomendada: 7,
    unidadRecomendada: 'cm de lamina',
    metodoAplicacion: 'inundacion',
    prioridad: 4,
    fuenteCientifica: 'FEDEARROZ - Manejo del agua en arroz Colombia.',
  },
  {
    codigo: 'R-RIEGO-006',
    nombre: 'Yuca riego solo en sequia extrema',
    descripcion: 'La yuca tolera sequia. Solo regar si hay signos visibles de marchitamiento.',
    tipoRecomendacion: 'riego',
    cultivoNombre: 'Yuca',
    faseAgronomica: 'crecimiento_vegetativo',
    estacion: 'seca',
    diasSinRiegoMinimo: 30,
    accionSugerida:
      'La yuca tolera sequia. Solo regar si hay signos visibles de marchitamiento sostenido. Riego ligero, evitar encharcamiento.',
    dosisRecomendada: 20,
    unidadRecomendada: 'L/planta',
    metodoAplicacion: 'goteo',
    prioridad: 2,
    fuenteCientifica: 'AGROSAVIA - Manual manejo yuca industrial Caribe colombiano.',
  },
  {
    codigo: 'R-RIEGO-007',
    nombre: 'Mango pre-floracion suspender riego',
    descripcion: 'Mango requiere estres hidrico controlado para diferenciar yemas florales.',
    tipoRecomendacion: 'riego',
    cultivoNombre: 'Mango',
    faseAgronomica: 'pre_floracion',
    estacion: 'seca',
    accionSugerida:
      'Suspender riego para inducir floracion. Mango requiere estres hidrico controlado para diferenciar yemas florales.',
    dosisRecomendada: 0,
    unidadRecomendada: 'L (suspension)',
    prioridad: 3,
    fuenteCientifica: 'FAO - Manejo plagas y enfermedades mango azucar Magdalena.',
  },
  {
    codigo: 'R-RIEGO-008',
    nombre: 'Mango fructificacion reanudar riego',
    tipoRecomendacion: 'riego',
    cultivoNombre: 'Mango',
    faseAgronomica: 'fructificacion',
    diasSinRiegoMinimo: 7,
    accionSugerida: 'Reanudar riego despues de cuajado de frutos para llenado.',
    dosisRecomendada: 100,
    unidadRecomendada: 'L/arbol/semana',
    metodoAplicacion: 'goteo',
    frecuenciaDias: 7,
    prioridad: 4,
    fuenteCientifica: 'FAO mango Magdalena.',
  },
  {
    codigo: 'R-RIEGO-009',
    nombre: 'Cafe asegurar humedad post-floracion',
    descripcion: 'El cafe sincroniza floraciones masivas tras sequias breves.',
    tipoRecomendacion: 'riego',
    cultivoNombre: 'Café',
    faseAgronomica: 'floracion',
    estacion: 'transicion',
    accionSugerida:
      'El cafe sincroniza floraciones masivas tras sequias breves. Asegurar suelo humedo durante 15 dias post-floracion.',
    metodoAplicacion: 'aspersion',
    frecuenciaDias: 3,
    prioridad: 4,
    fuenteCientifica: 'CENICAFE - Manejo agronomico del cafe.',
  },
  {
    codigo: 'R-RIEGO-010',
    nombre: 'Palma de aceite regimen constante en seca',
    tipoRecomendacion: 'riego',
    cultivoNombre: 'Palma de aceite',
    estacion: 'seca',
    diasSinRiegoMinimo: 5,
    accionSugerida: 'Mantener humedad constante. Deficit hidrico reduce racimos y aceite.',
    dosisRecomendada: 175,
    unidadRecomendada: 'L/palma/semana',
    metodoAplicacion: 'goteo',
    frecuenciaDias: 7,
    prioridad: 4,
    fuenteCientifica: 'CENIPALMA - Manejo agronomico palma de aceite.',
  },
];
