import { ReglaSeed } from './index';

/**
 * 20 reglas FITOSANITARIAS contra PLAGAS - Sprint 4 AgroField
 * Fuentes: ICA, AGROSAVIA, CENICAFE, CENIPALMA, CIAT, ADAMA, BASF, Bayer
 */
export const reglasPlagas: ReglaSeed[] = [
  {
    codigo: 'R-PLAGA-001',
    nombre: 'Sigatoka negra banano severidad media',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Banano',
    plagaNombre: 'Sigatoka negra',
    severidadMinima: 'media',
    accionSugerida:
      'Aplicar fungicida sistemico. Programa preventivo cada 10-14 dias en zona bananera del Magdalena (30-35 ciclos anuales).',
    productoSugerido: 'Mancozeb 80% WP, o Tridemorf, o Triazol (propiconazol)',
    dosisRecomendada: 2.25,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_foliar',
    frecuenciaDias: 12,
    prioridad: 5,
    fuenteCientifica:
      'Manejo Sigatoka Negra Zona Bananera Magdalena (Musalit). ICA Resolucion plagas musaceas.',
  },
  {
    codigo: 'R-PLAGA-002',
    nombre: 'Sigatoka negra severidad baja (preventivo)',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Banano',
    plagaNombre: 'Sigatoka negra',
    severidadMinima: 'baja',
    accionSugerida:
      'Aplicacion preventiva multisitio. Programa preventivo reduce riesgo de resistencia.',
    productoSugerido: 'Mancozeb (Control 720 SC - ICA 1030) o Polyram DF (ICA 2446)',
    dosisRecomendada: 1.75,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_foliar',
    frecuenciaDias: 17,
    prioridad: 3,
    fuenteCientifica: 'ADAMA Colombia - Fungicida Control 720 SC. BASF Colombia - Polyram DF.',
  },
  {
    codigo: 'R-PLAGA-003',
    nombre: 'Sigatoka negra severidad alta o critica',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Banano',
    plagaNombre: 'Sigatoka negra',
    severidadMinima: 'alta',
    accionSugerida:
      'Rotacion de fungicidas: sistemico + protectante. Combinar accion curativa y preventiva.',
    productoSugerido: 'Siganex SC60 0.4 L/ha + Mancozeb 2.0 kg/ha (rotacion)',
    dosisRecomendada: 0.4,
    unidadRecomendada: 'L/ha (Siganex)',
    metodoAplicacion: 'aspersion_foliar',
    frecuenciaDias: 8,
    prioridad: 5,
    fuenteCientifica: 'Bayer Colombia - Siganex SC60 control sigatoka. BASF - Opus 12.5 SC banano.',
  },
  {
    codigo: 'R-PLAGA-004',
    nombre: 'Moko del platano (CUARENTENARIA - reportar al ICA)',
    descripcion: 'Plaga cuarentenaria oficial. No hay control curativo.',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Plátano',
    plagaNombre: 'Moko del plátano',
    severidadMinima: 'baja',
    accionSugerida:
      'REPORTAR INMEDIATAMENTE al ICA. Erradicar plantas afectadas y un radio de 5 m. Desinfectar herramientas con formol o yodo. No hay control curativo.',
    productoSugerido: 'Formol al 5% para suelo / Biofungicidas (extractos vegetales)',
    dosisRecomendada: 20,
    unidadRecomendada: 'L/sitio afectado',
    metodoAplicacion: 'riego_localizado',
    prioridad: 5,
    fuenteCientifica:
      'ICA - Resolucion 1454. AGROSAVIA - Desarrollo medidas manejo Moko platano. ICA Magdalena Cundinamarca.',
  },
  {
    codigo: 'R-PLAGA-005',
    nombre: 'Gusano cogollero maiz larvas pequenas',
    descripcion: 'Es el momento optimo de control (estadios L1-L3).',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Maíz',
    plagaNombre: 'Gusano cogollero',
    severidadMinima: 'baja',
    accionSugerida:
      'Aplicar insecticida sobre el cogollo con larvas pequenas. Es el momento optimo de control.',
    productoSugerido: 'Clorantraniliprole o Lambda-cyhalothrin o Lufenuron',
    dosisRecomendada: 200,
    unidadRecomendada: 'cc/ha',
    metodoAplicacion: 'aspersion_dirigida_cogollo',
    prioridad: 5,
    fuenteCientifica:
      'ICA - El gusano cogollero del maiz, su control. CIMMYT-ICA. Zhiminaicela et al. (2024).',
  },
  {
    codigo: 'R-PLAGA-006',
    nombre: 'Gusano cogollero severidad alta (rotacion)',
    descripcion: 'Para evitar resistencia, rotar ingredientes activos.',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Maíz',
    plagaNombre: 'Gusano cogollero',
    severidadMinima: 'alta',
    accionSugerida:
      'Rotar ingredientes activos para evitar resistencia. Combinar con control biologico (Trichogramma).',
    productoSugerido: 'Spinetoram / Metomil 90% / Emamectin benzoate (rotar)',
    metodoAplicacion: 'aspersion_+_biologico',
    prioridad: 5,
    fuenteCientifica:
      'Velez M et al. (2021) - Metomil 90% control cogollero. ICA Resolucion MIP maiz.',
  },
  {
    codigo: 'R-PLAGA-007',
    nombre: 'Mosca blanca yuca (vector de virus)',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Yuca',
    plagaNombre: 'Mosca blanca',
    severidadMinima: 'media',
    accionSugerida:
      'Aplicar insecticida sistemico. Monitorear poblaciones cada semana. Importante porque es vector de virus.',
    productoSugerido: 'Imidacloprid o Thiamethoxam',
    dosisRecomendada: 250,
    unidadRecomendada: 'cc/ha',
    metodoAplicacion: 'aspersion_foliar',
    frecuenciaDias: 15,
    prioridad: 4,
    fuenteCientifica: 'AGROSAVIA - Manual yuca Caribe. CIAT - Mosca blanca yuca tropical.',
  },
  {
    codigo: 'R-PLAGA-008',
    nombre: 'Acaros yuca zona seca Magdalena',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Yuca',
    estacion: 'seca',
    severidadMinima: 'media',
    accionSugerida:
      'Liberar acaros depredadores (Typhlodromalus aripo, Neoseiulus idaeus). Solo usar acaricida si severidad critica.',
    productoSugerido: 'Bio-control: T. aripo / Quimico: Abamectina si critico',
    dosisRecomendada: 150,
    unidadRecomendada: 'depredadores/planta',
    metodoAplicacion: 'biologico',
    prioridad: 3,
    fuenteCientifica:
      'Pivijay Magdalena - estudios resistencia (CIAT 1999). AGROSAVIA control biologico.',
  },
  {
    codigo: 'R-PLAGA-009',
    nombre: 'Broca del cafe (>2% frutos infestados)',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Café',
    plagaNombre: 'Broca del café',
    severidadMinima: 'media',
    accionSugerida:
      'Re-Re-Re: recoleccion manual + repase + control biologico Beauveria bassiana. Usar trampas con etanol+metanol.',
    productoSugerido: 'Beauveria bassiana / Trampas con cebo',
    metodoAplicacion: 'aspersion_+_recoleccion_+_trampas',
    prioridad: 4,
    fuenteCientifica:
      'CENICAFE - Manejo de la broca del cafe. ICA - plagas control oficial cafetero.',
  },
  {
    codigo: 'R-PLAGA-010',
    nombre: 'Roya del cafe (5-10% infeccion)',
    descripcion: 'La roya es una de las enfermedades mas catastroficas historicamente.',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Café',
    plagaNombre: 'Roya del café',
    severidadMinima: 'media',
    accionSugerida:
      'Aplicar fungicida sistemico. La roya es una de las enfermedades mas catastroficas historicamente.',
    productoSugerido: 'Opus 12.5 SC (BASF) - Epoxiconazol',
    dosisRecomendada: 0.5,
    unidadRecomendada: 'L/ha',
    metodoAplicacion: 'aspersion_foliar',
    frecuenciaDias: 37,
    prioridad: 5,
    fuenteCientifica: 'BASF - Opus 12.5 SC roya cafe. CENICAFE - Manejo enfermedades cafeteras.',
  },
  {
    codigo: 'R-PLAGA-011',
    nombre: 'Roya del cafe severidad alta (variedad resistente)',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Café',
    plagaNombre: 'Roya del café',
    severidadMinima: 'alta',
    accionSugerida:
      'Renovar con variedad resistente (Castilla, Tabi, Cenicafe 1). En el corto plazo: aplicacion intensiva de triazol + estrobilurina.',
    productoSugerido: 'Triazol + Estrobilurina (rotacion)',
    metodoAplicacion: 'aspersion_foliar',
    prioridad: 5,
    fuenteCientifica: 'CENICAFE - Variedades resistentes y manejo intensivo roya.',
  },
  {
    codigo: 'R-PLAGA-012',
    nombre: 'Picudo palma (vector anillo rojo y PC)',
    descripcion: 'Vector de enfermedades cuarentenarias. Captura masiva con feromona.',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Palma de aceite',
    plagaNombre: 'Picudo del banano',
    severidadMinima: 'baja',
    accionSugerida:
      'Instalar trampas con feromona Rhynchophorol + cana de azucar. Captura masiva. Reemplazar feromona cada 3 meses.',
    productoSugerido: 'Feromona Rhynchophorol',
    dosisRecomendada: 1,
    unidadRecomendada: 'trampa/ha cada 200 m',
    metodoAplicacion: 'trampeo',
    frecuenciaDias: 90,
    prioridad: 5,
    fuenteCientifica: 'ICA - Manejo del picudo Rhynchophorus palmarum. CENIPALMA palma Magdalena.',
  },
  {
    codigo: 'R-PLAGA-013',
    nombre: 'Mosca de la fruta mango (trampas McPhail)',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Mango',
    severidadMinima: 'media',
    accionSugerida:
      'Instalar trampas McPhail. Aplicar control biologico con Beauveria bassiana o entomopatogenos.',
    productoSugerido: 'Trampa McPhail con cebo proteinico / Beauveria',
    dosisRecomendada: 1,
    unidadRecomendada: 'trampa/ha',
    metodoAplicacion: 'trampeo_+_biologico',
    prioridad: 4,
    fuenteCientifica: 'AGROSAVIA - Manejo plagas mango Magdalena (proyecto proinv869).',
  },
  {
    codigo: 'R-PLAGA-014',
    nombre: 'Trips inflorescencias mango (control biologico)',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Mango',
    plagaNombre: 'Trips',
    faseAgronomica: 'floracion',
    severidadMinima: 'media',
    accionSugerida:
      'Liberacion de Orius sp. (depredador). Productos compatibles con control natural.',
    productoSugerido: 'Orius sp. / Spinosad',
    dosisRecomendada: 7,
    unidadRecomendada: 'Orius/m2 de copa',
    metodoAplicacion: 'biologico_+_quimico_selectivo',
    prioridad: 4,
    fuenteCientifica: 'AGROSAVIA - Estrategias trips mango.',
  },
  {
    codigo: 'R-PLAGA-015',
    nombre: 'Antracnosis frutales (mango/papaya/aguacate)',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Mango',
    plagaNombre: 'Antracnosis',
    severidadMinima: 'media',
    accionSugerida: 'Aplicacion preventiva en pre-cosecha. Eliminar frutos enfermos.',
    productoSugerido: 'Mancozeb o Azoxistrobina',
    dosisRecomendada: 2,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_foliar',
    frecuenciaDias: 14,
    prioridad: 4,
    fuenteCientifica: 'Asohofrucol - Guia ilustrada enfermedades frutales Colombia.',
  },
  {
    codigo: 'R-PLAGA-016',
    nombre: 'Pulgones (control en fase vegetativa)',
    tipoRecomendacion: 'fitosanitario_plaga',
    plagaNombre: 'Pulgones',
    severidadMinima: 'media',
    accionSugerida:
      'Aplicar insecticida sistemico de baja toxicidad. Promover enemigos naturales (Coccinellidae).',
    productoSugerido: 'Imidacloprid o Acetamiprid',
    dosisRecomendada: 200,
    unidadRecomendada: 'cc/ha',
    metodoAplicacion: 'aspersion_foliar',
    prioridad: 3,
    fuenteCientifica: 'ICA - Manejo integrado plagas hortalizas y frutales.',
  },
  {
    codigo: 'R-PLAGA-017',
    nombre: 'Tizon temprano (Alternaria)',
    tipoRecomendacion: 'fitosanitario_plaga',
    plagaNombre: 'Tizón temprano',
    severidadMinima: 'media',
    accionSugerida: 'Fungicida preventivo. Eliminar restos vegetales infectados. Rotar cultivos.',
    productoSugerido: 'Mancozeb o Clorotalonil',
    dosisRecomendada: 2.5,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'aspersion_foliar',
    frecuenciaDias: 10,
    prioridad: 4,
    fuenteCientifica: 'ICA - Manejo Alternaria solani solanaceas.',
  },
  {
    codigo: 'R-PLAGA-018',
    nombre: 'Virus mosaico de la yuca',
    descripcion: 'No hay tratamiento curativo. Control del vector (mosca blanca) es clave.',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Yuca',
    plagaNombre: 'Virus del mosaico de la yuca',
    severidadMinima: 'baja',
    accionSugerida:
      'No hay tratamiento curativo. Eliminar plantas enfermas, usar material de siembra sano y controlar el vector (mosca blanca).',
    productoSugerido: 'Sin producto curativo - control de vector',
    metodoAplicacion: 'erradicacion_+_control_vector',
    prioridad: 5,
    fuenteCientifica: 'CIAT - Virus mosaico yuca. AGROSAVIA Caribe.',
  },
  {
    codigo: 'R-PLAGA-019',
    nombre: 'Nematodo del nudo (Meloidogyne)',
    tipoRecomendacion: 'fitosanitario_plaga',
    plagaNombre: 'Nematodo del nudo',
    severidadMinima: 'media',
    accionSugerida:
      'Aplicar nematicida al suelo + rotacion con cultivo no hospedante. Solarizacion del suelo en epoca seca.',
    productoSugerido: 'Carbofuran o nematicida biologico (Paecilomyces)',
    dosisRecomendada: 30,
    unidadRecomendada: 'kg/ha',
    metodoAplicacion: 'edafica_+_rotacion',
    prioridad: 4,
    fuenteCientifica: 'AGROSAVIA - Manejo nematodos suelo Caribe.',
  },
  {
    codigo: 'R-PLAGA-020',
    nombre: 'Hormiga arriera (cebos localizados)',
    descripcion: 'NO destruir nido (provoca dispersion). Cebos en caminos.',
    tipoRecomendacion: 'fitosanitario_plaga',
    cultivoNombre: 'Yuca',
    plagaNombre: 'Coquito',
    severidadMinima: 'media',
    accionSugerida:
      'Localizar hormigueros y aplicar cebos. NO destruir el nido (provoca dispersion).',
    productoSugerido: 'Cebo con Fipronil o Sulfluramida',
    dosisRecomendada: 10,
    unidadRecomendada: 'g/m2 de hormiguero',
    metodoAplicacion: 'cebo_localizado',
    prioridad: 4,
    fuenteCientifica: 'AGROSAVIA - Manejo hormiga arriera Caribe.',
  },
];
