import { MigrationInterface, QueryRunner } from "typeorm";

export class IncreaseMetodoAplicacionLength1779579431397 implements MigrationInterface {
    name = 'IncreaseMetodoAplicacionLength1779579431397'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "lotes" DROP CONSTRAINT "FK_lotes_cultivoActual"`);
        await queryRunner.query(`ALTER TABLE "lotes" DROP CONSTRAINT "FK_lotes_municipio"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cultivos_nombre_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cultivos_nombreCientifico_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_municipios_codigoDane_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_municipios_nombre_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lotes_cultivoActualId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lotes_municipioId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_plagas_nombre_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_plagas_nombreCientifico_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_hallazgos_loteId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_hallazgos_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_hallazgos_fecha"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_hallazgos_severidad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tratamientos_loteId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tratamientos_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tratamientos_fecha"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_siembras_loteId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_siembras_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_siembras_fecha"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_riego_loteId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_riego_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_riego_fecha"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_observaciones_loteId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_observaciones_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_observaciones_fecha"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fertilizantes_nombre_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fertilizacion_loteId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fertilizacion_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fertilizacion_fecha"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tipos_suelo_nombre_active"`);
        await queryRunner.query(`CREATE TABLE "estado_terreno" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loteId" uuid NOT NULL, "siembraId" uuid, "estado" character varying(50) NOT NULL, "tipoSueloId" uuid, "notas" text, "userId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_1d156280051b12c78655a414558" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_27620aa317b91fc445849b4759" ON "estado_terreno" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_76d8975922fd4d664cb24c1de6" ON "estado_terreno" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a567220b082b7e734a6aa61c71" ON "estado_terreno" ("loteId") `);
        await queryRunner.query(`ALTER TABLE "hallazgos" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hallazgos" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tratamientos" DROP COLUMN "metodoAplicacion"`);
        await queryRunner.query(`ALTER TABLE "tratamientos" ADD "metodoAplicacion" character varying(150)`);
        await queryRunner.query(`ALTER TABLE "tratamientos" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tratamientos" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "siembras" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "siembras" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "riego" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "riego" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "observaciones" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "observaciones" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "fertilizacion" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "fertilizacion" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8ce79aa1393abc27903cba0fdd" ON "cultivos" ("nombre") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_39a22432cc666b9d849424b156" ON "cultivos" ("nombreCientifico") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5cd6503ef860fe03b7beaad755" ON "municipios" ("nombre") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_19644bbe082402d0daae98a5de" ON "municipios" ("codigoDane") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2ea727581a72bf8a82e5b06043" ON "plagas" ("nombre") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bb78d30c3e341d154aa55b8502" ON "plagas" ("nombreCientifico") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_5bb6737b12c6a169b2470bd933" ON "hallazgos" ("severidad") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6157e3c3bf24a77fdc92d2fcd" ON "hallazgos" ("fecha") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a054b1cda31684dd26005c39c" ON "hallazgos" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_73153621e5b99c7e3d6ce35fdc" ON "hallazgos" ("loteId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f60937975a0c9de2be62395a5" ON "tratamientos" ("fecha") `);
        await queryRunner.query(`CREATE INDEX "IDX_44ec87ff98f58943694271b5c1" ON "tratamientos" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e33dc4f1078f65a97b16eae2de" ON "tratamientos" ("loteId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bc5713a1ba2150bc717a6d3bb4" ON "siembras" ("fecha") `);
        await queryRunner.query(`CREATE INDEX "IDX_d79b5b2345f584f55bed44bafd" ON "siembras" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5953c17f9326dab82e2de8a169" ON "siembras" ("loteId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c4a4160381e8717cce5f360a7" ON "riego" ("fecha") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b173f37c36333574844946a19" ON "riego" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e2c8348b8c12c099538d09718" ON "riego" ("loteId") `);
        await queryRunner.query(`CREATE INDEX "IDX_824bb594969dffa2b957dbe970" ON "observaciones" ("fecha") `);
        await queryRunner.query(`CREATE INDEX "IDX_a55a560cbd86ba3c11ae4df05c" ON "observaciones" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_da93056160d5d14c18e1b3f6ec" ON "observaciones" ("loteId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_58b1f01fe958d7a24e4feba4fb" ON "fertilizantes" ("nombre") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_5bebbda033bc47d17d629f6d00" ON "fertilizacion" ("fecha") `);
        await queryRunner.query(`CREATE INDEX "IDX_1653358f2fa29449ca15a402bb" ON "fertilizacion" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f27ef2aee087545ca576fad3a5" ON "fertilizacion" ("loteId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_86a63ddecdc8e56ba97775c950" ON "tipos_suelo" ("nombre") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`ALTER TABLE "lotes" ADD CONSTRAINT "FK_eda39eb0e81adccedf20f0a2859" FOREIGN KEY ("cultivoActualId") REFERENCES "cultivos"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lotes" ADD CONSTRAINT "FK_0b5751e3d82d4208b08502402c5" FOREIGN KEY ("municipioId") REFERENCES "municipios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "estado_terreno" ADD CONSTRAINT "FK_a567220b082b7e734a6aa61c71c" FOREIGN KEY ("loteId") REFERENCES "lotes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "estado_terreno" ADD CONSTRAINT "FK_949ba0b8f35c74728db12522651" FOREIGN KEY ("siembraId") REFERENCES "siembras"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "estado_terreno" ADD CONSTRAINT "FK_f72f27cf097cb0e52bcebd8de62" FOREIGN KEY ("tipoSueloId") REFERENCES "tipos_suelo"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "estado_terreno" ADD CONSTRAINT "FK_76d8975922fd4d664cb24c1de62" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "estado_terreno" DROP CONSTRAINT "FK_76d8975922fd4d664cb24c1de62"`);
        await queryRunner.query(`ALTER TABLE "estado_terreno" DROP CONSTRAINT "FK_f72f27cf097cb0e52bcebd8de62"`);
        await queryRunner.query(`ALTER TABLE "estado_terreno" DROP CONSTRAINT "FK_949ba0b8f35c74728db12522651"`);
        await queryRunner.query(`ALTER TABLE "estado_terreno" DROP CONSTRAINT "FK_a567220b082b7e734a6aa61c71c"`);
        await queryRunner.query(`ALTER TABLE "lotes" DROP CONSTRAINT "FK_0b5751e3d82d4208b08502402c5"`);
        await queryRunner.query(`ALTER TABLE "lotes" DROP CONSTRAINT "FK_eda39eb0e81adccedf20f0a2859"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86a63ddecdc8e56ba97775c950"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f27ef2aee087545ca576fad3a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1653358f2fa29449ca15a402bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5bebbda033bc47d17d629f6d00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58b1f01fe958d7a24e4feba4fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da93056160d5d14c18e1b3f6ec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a55a560cbd86ba3c11ae4df05c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_824bb594969dffa2b957dbe970"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e2c8348b8c12c099538d09718"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b173f37c36333574844946a19"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c4a4160381e8717cce5f360a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5953c17f9326dab82e2de8a169"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d79b5b2345f584f55bed44bafd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc5713a1ba2150bc717a6d3bb4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e33dc4f1078f65a97b16eae2de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44ec87ff98f58943694271b5c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f60937975a0c9de2be62395a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_73153621e5b99c7e3d6ce35fdc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a054b1cda31684dd26005c39c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6157e3c3bf24a77fdc92d2fcd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5bb6737b12c6a169b2470bd933"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb78d30c3e341d154aa55b8502"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ea727581a72bf8a82e5b06043"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19644bbe082402d0daae98a5de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5cd6503ef860fe03b7beaad755"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39a22432cc666b9d849424b156"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ce79aa1393abc27903cba0fdd"`);
        await queryRunner.query(`ALTER TABLE "fertilizacion" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "fertilizacion" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "observaciones" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "observaciones" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "riego" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "riego" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "siembras" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "siembras" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tratamientos" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tratamientos" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tratamientos" DROP COLUMN "metodoAplicacion"`);
        await queryRunner.query(`ALTER TABLE "tratamientos" ADD "metodoAplicacion" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "hallazgos" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "hallazgos" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a567220b082b7e734a6aa61c71"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76d8975922fd4d664cb24c1de6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27620aa317b91fc445849b4759"`);
        await queryRunner.query(`DROP TABLE "estado_terreno"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_tipos_suelo_nombre_active" ON "tipos_suelo" ("nombre") WHERE ("deletedAt" IS NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_fertilizacion_fecha" ON "fertilizacion" ("fecha") `);
        await queryRunner.query(`CREATE INDEX "IDX_fertilizacion_userId" ON "fertilizacion" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fertilizacion_loteId" ON "fertilizacion" ("loteId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fertilizantes_nombre_active" ON "fertilizantes" ("nombre") WHERE ("deletedAt" IS NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_observaciones_fecha" ON "observaciones" ("fecha") `);
        await queryRunner.query(`CREATE INDEX "IDX_observaciones_userId" ON "observaciones" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_observaciones_loteId" ON "observaciones" ("loteId") `);
        await queryRunner.query(`CREATE INDEX "IDX_riego_fecha" ON "riego" ("fecha") `);
        await queryRunner.query(`CREATE INDEX "IDX_riego_userId" ON "riego" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_riego_loteId" ON "riego" ("loteId") `);
        await queryRunner.query(`CREATE INDEX "IDX_siembras_fecha" ON "siembras" ("fecha") `);
        await queryRunner.query(`CREATE INDEX "IDX_siembras_userId" ON "siembras" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_siembras_loteId" ON "siembras" ("loteId") `);
        await queryRunner.query(`CREATE INDEX "IDX_tratamientos_fecha" ON "tratamientos" ("fecha") `);
        await queryRunner.query(`CREATE INDEX "IDX_tratamientos_userId" ON "tratamientos" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_tratamientos_loteId" ON "tratamientos" ("loteId") `);
        await queryRunner.query(`CREATE INDEX "IDX_hallazgos_severidad" ON "hallazgos" ("severidad") `);
        await queryRunner.query(`CREATE INDEX "IDX_hallazgos_fecha" ON "hallazgos" ("fecha") `);
        await queryRunner.query(`CREATE INDEX "IDX_hallazgos_userId" ON "hallazgos" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_hallazgos_loteId" ON "hallazgos" ("loteId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_plagas_nombreCientifico_active" ON "plagas" ("nombreCientifico") WHERE ("deletedAt" IS NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_plagas_nombre_active" ON "plagas" ("nombre") WHERE ("deletedAt" IS NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_lotes_municipioId" ON "lotes" ("municipioId") `);
        await queryRunner.query(`CREATE INDEX "IDX_lotes_cultivoActualId" ON "lotes" ("cultivoActualId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_municipios_nombre_active" ON "municipios" ("nombre") WHERE ("deletedAt" IS NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_municipios_codigoDane_active" ON "municipios" ("codigoDane") WHERE ("deletedAt" IS NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cultivos_nombreCientifico_active" ON "cultivos" ("nombreCientifico") WHERE ("deletedAt" IS NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cultivos_nombre_active" ON "cultivos" ("nombre") WHERE ("deletedAt" IS NULL)`);
        await queryRunner.query(`ALTER TABLE "lotes" ADD CONSTRAINT "FK_lotes_municipio" FOREIGN KEY ("municipioId") REFERENCES "municipios"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lotes" ADD CONSTRAINT "FK_lotes_cultivoActual" FOREIGN KEY ("cultivoActualId") REFERENCES "cultivos"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
    }

}
